twilio:
  account_sid: ${TWILIO_SID}
  auth_token: ${TWILIO_TOKEN}
  trial_number: +13475376942
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL_DEPLOY}
    username: ${DB_USER_DEPLOY}
    password: ${DB_PASSWORD_DEPLOY}
  jpa:
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: contatomateusgd@gmail.com
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
          from: contatomateusgd@gmail.com
    default-encoding: UTF-8
    test-connection: false